services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: perl-plexapi-test
    ports:
      - "32400:32400/tcp"
    environment:
      TZ: UTC
      ADVERTISE_IP: http://127.0.0.1:32400/
    volumes:
      - ./plex-test-data/config:/config
      - ./plex-test-data/transcode:/transcode
      - ./plex-test-data/media:/data
    restart: "no"
